
# Mock data for Zootique application

ANIMALS = [
    {
        "id": 1, "zoo_id": 1,
        "name": "Leo", "species": "Lion", "habitat": "Savannah Zone", "status": "Healthy",
        "description": "Alpha male lion in the west enclosure.",
        "image_url": "https://images.unsplash.com/photo-1614027126733-149f7e808297?auto=format&fit=crop&q=80&w=400",
    },
    {
        "id": 2, "zoo_id": 1,
        "name": "Mina", "species": "Giraffe", "habitat": "Grassland Dome", "status": "Under Observation",
        "description": "Recently transferred and adapting to new habitat.",
        "image_url": "https://images.unsplash.com/photo-1547721064-da6cfb341d50?auto=format&fit=crop&q=80&w=400",
    },
    {
        "id": 3, "zoo_id": 2,
        "name": "Bessie", "species": "Cow", "habitat": "Dairy Barn", "status": "Healthy",
        "description": "Friendly dairy cow often featured during farm education tours.",
        "image_url": "https://images.unsplash.com/photo-1560200353-ce0a76b1d438?auto=format&fit=crop&q=80&w=400",
    },
    {
        "id": 4, "zoo_id": 3,
        "name": "Clover", "species": "Goat", "habitat": "Petting Yard", "status": "Healthy",
        "description": "Curious and gentle—perfect for the Hiraya petting area.",
        "image_url": "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&q=80&w=400",
    },
]

ZOOS = [
    {
        "id": 1,
        "name": "Lyger Zoo",
        "type": "Zoo Park",
        "type_slug": "zoo",
        "type_color": "#0d9b82",
        "location": "Laguna, PH",
        "description": "A modern zoo experience with curated habitats, family-friendly trails, and conservation-focused exhibits.",
        "image_url": "https://images.unsplash.com/photo-1549366021-9f761d040a94?auto=format&fit=crop&q=80&w=700",
        "price": 500.00,
        "rating": 4.8,
        "animal_count": 183,
        "exhibit_count": 12,
        "visitors_today": 256,
        "hours": "8:00 AM – 6:00 PM",
    },
    {
        "id": 2,
        "name": "Graco Farms",
        "type": "Farm Attraction",
        "type_slug": "farm",
        "type_color": "#d97706",
        "location": "Tagaytay, PH",
        "description": "Hands-on farm fun: barn tours, animal feeding, and seasonal harvest activities for families and school trips.",
        "image_url": "https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&q=80&w=700",
        "price": 350.00,
        "rating": 4.7,
        "animal_count": 60,
        "exhibit_count": 6,
        "visitors_today": 92,
        "hours": "8:00 AM – 5:00 PM",
    },
    {
        "id": 3,
        "name": "Hiraya Farms",
        "type": "Farm Attraction",
        "type_slug": "farm",
        "type_color": "#d97706",
        "location": "Batangas, PH",
        "description": "A scenic farm retreat featuring a petting yard, guided learning stations, and weekend family activities.",
        "image_url": "https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&q=80&w=700",
        "price": 350.00,
        "rating": 4.7,
        "animal_count": 60,
        "exhibit_count": 6,
        "visitors_today": 92,
        "hours": "8:00 AM – 5:00 PM",
    },
]

SERVICES = [
    {
        "id": 1, "zoo_id": 1,
        "name": "Guided Safari Tour",
        "category": "Tours",
        "price": 300,
        "price_label": "per person",
        "description": "Experience wildlife up close with expert guides on this immersive safari adventure.",
        "duration": "2 hours",
        "max_guests": 20,
        "rating": 4.9,
        "review_count": 142,
        "image_url": "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&q=80&w=600",
    },
    {
        "id": 2, "zoo_id": 1,
        "name": "Lion Feeding Experience",
        "category": "Encounters",
        "price": 500,
        "price_label": "per person",
        "description": "Get up close with majestic lions during their feeding time with professional supervision.",
        "duration": "1 hour",
        "max_guests": 15,
        "rating": 4.8,
        "review_count": 89,
        "image_url": "https://images.unsplash.com/photo-1614027126733-149f7e808297?auto=format&fit=crop&q=80&w=600",
    },
    {
        "id": 3, "zoo_id": 2,
        "name": "Farm Learning Tour",
        "category": "Tours",
        "price": 250,
        "price_label": "per person",
        "description": "A guided walk through Graco Farms with feeding stops and short learning stations.",
        "duration": "1.5 hours",
        "max_guests": 25,
        "rating": 4.7,
        "review_count": 158,
        "image_url": "https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&q=80&w=600",
    },
    {
        "id": 4, "zoo_id": 3,
        "name": "Petting Yard Pass",
        "category": "Encounters",
        "price": 200,
        "price_label": "per person",
        "description": "Access to the Hiraya Farms petting yard with supervised animal interactions.",
        "duration": "1 hour",
        "max_guests": 30,
        "rating": 4.7,
        "review_count": 73,
        "image_url": "https://images.unsplash.com/photo-1546447147-2e2263d1c4e2?auto=format&fit=crop&q=80&w=600",
    },
    {
        "id": 5, "zoo_id": 1,
        "name": "General Admission",
        "category": "Admission",
        "price": 500,
        "price_label": "per person",
        "description": "Standard entry ticket for all ages to explore Lyger Zoo freely.",
        "duration": "Full day",
        "max_guests": 50,
        "rating": 4.5,
        "review_count": 320,
        "image_url": "https://images.unsplash.com/photo-1560805017-0ba3bc052062?auto=format&fit=crop&q=80&w=400",
    },
]

BOOKINGS = [
    {
        "id": "BK-1001",
        "visitor_name": "Juan Dela Cruz",
        "service_name": "Guided Safari Tour",
        "date": "April 25, 2024",
        "time": "2:00 PM",
        "guests": 4,
        "status": "Confirmed",
        "status_color": "confirmed",
        "amount": 300,
        "image_url": "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&q=80&w=80",
    },
    {
        "id": "BK-1002",
        "visitor_name": "Maria Clara",
        "service_name": "Lion Feeding Experience",
        "date": "May 2, 2024",
        "time": "10:00 AM",
        "guests": 2,
        "status": "Pending",
        "status_color": "pending",
        "amount": 500,
        "image_url": "https://images.unsplash.com/photo-1614027126733-149f7e808297?auto=format&fit=crop&q=80&w=80",
    },
    {
        "id": "BK-1003",
        "visitor_name": "Pedro Penduko",
        "service_name": "Night Safari Adventure",
        "date": "May 10, 2024",
        "time": "6:30 PM",
        "guests": 3,
        "status": "Cancelled",
        "status_color": "cancelled",
        "amount": 600,
        "image_url": "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&q=80&w=80",
    },
]

EVENTS = [
    {"id": 1, "name": "Lion Feeding Show", "type": "Feeding", "time": "10:00 AM", "location": "Savannah Zone"},
    {"id": 2, "name": "Dolphin Performance", "type": "Show", "time": "1:00 PM", "location": "Aquatic Theater"},
    {"id": 3, "name": "Bird of Prey Demonstration", "type": "Show", "time": "3:30 PM", "location": "Open Air Arena"},
    {"id": 4, "name": "Elephant Feeding", "type": "Feeding", "time": "4:00 PM", "location": "River Plains"},
    {"id": 5, "name": "Night Safari Walk", "type": "Tour", "time": "7:00 PM", "location": "East Trail"},
]

PROMOTIONS = [
    {
        "id": 1,
        "title": "20% OFF",
        "name": "Summer Safari Discount",
        "code": "SAFARI20",
        "discount": "20%",
        "color": "dark-green",
        "valid_until": "2026-05-31",
        "valid_until_display": "May 31, 2024",
    },
    {
        "id": 2,
        "title": "Kids Go Free",
        "name": "Free child admission",
        "code": "KIDSGO",
        "discount": "100%",
        "color": "amber",
        "valid_until": "2026-06-15",
        "valid_until_display": "June 15, 2024",
    },
    {
        "id": 3,
        "title": "30% OFF",
        "name": "Night Safari Special",
        "code": "NIGHT30",
        "discount": "30%",
        "color": "dark-green",
        "valid_until": "2026-04-30",
        "valid_until_display": "April 30, 2024",
    },
]

FEEDBACKS = [
    {
        "id": 1, "visitor_name": "Elena Torres", "rating": 5,
        "comment": "Amazing experience! The guided tour was very informative.",
        "date": "2026-03-25",
    },
    {
        "id": 2, "visitor_name": "Ricardo Gomez", "rating": 4,
        "comment": "Great zoo, but some areas were a bit crowded.",
        "date": "2026-03-26",
    },
]
