"""tenant_notnull

Revision ID: e87a214ef978
Revises: f0ad3ee291e5
Create Date: 2026-04-17 19:05:04.199340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87a214ef978'
down_revision = 'f0ad3ee291e5'
branch_labels = None
depends_on = None


def upgrade():
    # Policy: enforce strong tenant isolation.
    # For legacy/dev data, delete rows that have NULL zoo_id rather than attempting to guess a tenant.
    # Booking payments may reference bookings, so delete dependent rows first.

    op.execute("DELETE FROM booking_payments WHERE zoo_id IS NULL")
    op.execute(
        "DELETE FROM booking_payments WHERE booking_id IN (SELECT id FROM bookings WHERE zoo_id IS NULL)"
    )
    op.execute("DELETE FROM bookings WHERE zoo_id IS NULL")
    op.execute("DELETE FROM events WHERE zoo_id IS NULL")
    op.execute("DELETE FROM feedbacks WHERE zoo_id IS NULL")
    op.execute("DELETE FROM promotions WHERE zoo_id IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_payments', schema=None) as batch_op:
        batch_op.alter_column('zoo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('zoo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('zoo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('zoo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('zoo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('zoo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('zoo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('zoo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('zoo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('booking_payments', schema=None) as batch_op:
        batch_op.alter_column('zoo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
