"""baseline

Revision ID: f0ad3ee291e5
Revises: 
Create Date: 2026-04-17 18:59:50.388535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ad3ee291e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration', sa.String(length=10), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('zoos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('habitat', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoo_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoo_id', sa.Integer(), nullable=True),
    sa.Column('visitor_name', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_feedbacks_rating_range'),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoo_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('promo_type', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('discount', sa.String(length=20), nullable=True),
    sa.Column('valid_until', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('zoo_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('zoo_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoo_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zoo_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('map_image_url', sa.String(length=500), nullable=True),
    sa.Column('panorama_360_url', sa.String(length=800), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('zoo_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_staff_user_id', sa.Integer(), nullable=True),
    sa.Column('visitor_name', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('booking_time', sa.Time(), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("payment_status IN ('unpaid', 'paid', 'refunded', 'failed')", name='ck_bookings_payment_status'),
    sa.CheckConstraint("status IN ('Pending', 'Confirmed', 'Cancelled')", name='ck_bookings_status'),
    sa.CheckConstraint('amount >= 0', name='ck_bookings_amount_non_negative'),
    sa.CheckConstraint('guests >= 1', name='ck_bookings_guests_min'),
    sa.ForeignKeyConstraint(['assigned_staff_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_bookings_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_bookings_zoo_created', ['zoo_id', 'created_at'], unique=False)

    op.create_table('staff_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoo_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'done')", name='ck_staff_tasks_status'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('paid', 'refunded', 'failed')", name='ck_subscription_payments_status'),
    sa.CheckConstraint('amount >= 0', name='ck_subscription_payments_amount_non_negative'),
    sa.ForeignKeyConstraint(['subscription_id'], ['zoo_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zoo_admin_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_zoo_admin_feedback_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.String(length=20), nullable=False),
    sa.Column('zoo_id', sa.Integer(), nullable=True),
    sa.Column('payer_user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('paid', 'failed', 'refunded')", name='ck_booking_payments_status'),
    sa.CheckConstraint('amount >= 0', name='ck_booking_payments_amount_non_negative'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zoo_id'], ['zoos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'idempotency_key', name='uq_booking_payment_idempotency'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('booking_payments', schema=None) as batch_op:
        batch_op.create_index('ix_booking_payments_booking_created', ['booking_id', 'created_at'], unique=False)

    op.create_table('zoo_admin_feedback_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['zoo_admin_feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoo_admin_feedback_replies')
    with op.batch_alter_table('booking_payments', schema=None) as batch_op:
        batch_op.drop_index('ix_booking_payments_booking_created')

    op.drop_table('booking_payments')
    op.drop_table('zoo_admin_feedback')
    op.drop_table('subscription_payments')
    op.drop_table('staff_tasks')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_bookings_zoo_created')
        batch_op.drop_index('ix_bookings_user_created')

    op.drop_table('bookings')
    op.drop_table('zoo_zones')
    op.drop_table('zoo_subscriptions')
    op.drop_table('users')
    op.drop_table('services')
    op.drop_table('promotions')
    op.drop_table('feedbacks')
    op.drop_table('events')
    op.drop_table('animals')
    op.drop_table('zoos')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
